/* Media capture helpers for the Claude desktop app's built-in browser (Claude_Browser tools).
   Why: the cloud sandbox cannot reach YouTube, storage.googleapis.com, company CDNs etc., and the browser pane
   cannot download files. So we draw the media onto a full-viewport canvas and take screenshots; every
   screenshot carries a 20-bit barcode with the timestamp/tile id so it can be decoded back into frames
   (see shows/kd-tech-daily/research/decode_caps.py and mkbatch.py).

   Setup per page:
     1. resize_window to 800x940 (two 800x450 frames + two 20 px barcodes fit exactly)
     2. paste the VIDEO block (YouTube watch page; press play once, pause, set quality hd1080) or the IMAGE block
     3. VIDEO: run browser_batch actions generated by `python3 mkbatch.py <t0> <t1> <fps>`:
          javascript_exec "await PAIR(t1, t2)" -> screenshot scale 0.1 (primes a repaint) -> screenshot scale 1
        The tiny priming screenshot matters: without it the pane sometimes returns the previous paint.
     4. IMAGE: await TILES(index, 0, 1) then TILES(index, 2, 3): a 1600x900 crop in four 800x450 tiles
     5. in the cloud sandbox: python3 decode_caps.py <name> <since_epoch_ms>  -> caps/<name>/<ms>.jpg
     6. smooth to 30 fps: ffmpeg -framerate 12 -i %04d.jpg -vf "setpts=1.25*PTS,minterpolate=fps=30:mi_mode=mci" ...
   Barcodes: frames use round(t*1000); image tiles use 1000 + index*10 + tile (or 2000+ for a second page).
   Always reset the viewport afterwards (resize_window preset "desktop"). Credit the source on screen. */

// ---------- shared ----------
document.documentElement.style.overflow = 'hidden';
window.CV = () => { let c = document.getElementById('cap'); if (!c) { c = document.createElement('canvas'); c.id = 'cap'; document.body.appendChild(c); }
  Object.assign(c.style, { position: 'fixed', left: '0', top: '0', width: innerWidth + 'px', height: innerHeight + 'px', zIndex: 2147483647, background: '#000', display: 'block' });
  if (c.width !== innerWidth || c.height !== innerHeight) { c.width = innerWidth; c.height = innerHeight; } return c; };
window.CODE = (g, y, val) => { g.fillStyle = '#000'; g.fillRect(0, y, 800, 20); for (let b = 0; b < 20; b++) { g.fillStyle = ((val >> (19 - b)) & 1) ? '#fff' : '#000'; g.fillRect(b * 40 + 2, y + 2, 36, 16); } };

// ---------- VIDEO (YouTube watch page) ----------
window.V = () => document.querySelector('video');
window.SEEK = t => new Promise(r => { const v = V(); const f = () => { v.removeEventListener('seeked', f); r(true); }; v.addEventListener('seeked', f); v.currentTime = t; setTimeout(() => r(false), 6000); });
window.SIG = g => { g.drawImage(V(), 0, 0, 64, 36); const d = g.getImageData(0, 0, 64, 36).data; let s = 0; for (let i = 0; i < d.length; i += 37) s = (s * 31 + d[i]) % 1000003; return s; };
// seek until two consecutive decodes match (YouTube sometimes paints the previous frame first)
window.STABLE = async t => { const tmp = document.createElement('canvas'); tmp.width = 64; tmp.height = 36; const g = tmp.getContext('2d'); let prev = -1;
  for (let k = 0; k < 4; k++) { await SEEK(t); await new Promise(r => setTimeout(r, 90)); const s = SIG(g); if (s === prev) return true; prev = s; } return false; };
// contact sheet to find the good moments: await GRID(t0, step, count)
window.GRID = async (t0, dt, n, cols = 5) => { const c = CV(), W = c.width, H = c.height, g = c.getContext('2d'); g.fillStyle = '#000'; g.fillRect(0, 0, W, H);
  const cw = W / cols, ch = cw * 9 / 16; g.font = '13px sans-serif';
  for (let i = 0; i < n; i++) { const t = t0 + i * dt; if (t > V().duration) break; await STABLE(t); const x = (i % cols) * cw, y = Math.floor(i / cols) * ch;
    g.drawImage(V(), x, y, cw, ch); g.fillStyle = '#000'; g.fillRect(x, y, 52, 15); g.fillStyle = '#ff0'; g.fillText(t.toFixed(2), x + 2, y + 12); } return [W, H]; };
// two frames per screenshot, each with its barcode
window.PAIR = async (t1, t2) => { const c = CV(), W = c.width, g = c.getContext('2d'); g.fillStyle = '#202020'; g.fillRect(0, 0, c.width, c.height);
  const a = await STABLE(t1); g.drawImage(V(), 0, 0, W, 450); CODE(g, 450, Math.round(t1 * 1000)); let b = true;
  if (t2 != null) { b = await STABLE(t2); g.drawImage(V(), 0, 470, W, 450); CODE(g, 920, Math.round(t2 * 1000)); } else CODE(g, 920, 0);
  await new Promise(r => setTimeout(r, 150)); return [a, b, innerWidth, innerHeight]; };

// ---------- IMAGE (any page) ----------
// window.IMGS = [...document.images].filter(i => i.naturalWidth > 500);   // or load og:image / srcset URLs with new Image()
window.TILES = async (idx, a, b, base = 1000) => { const im = IMGS[idx]; if (im.decode) await im.decode().catch(() => { });
  const c = CV(), g = c.getContext('2d'); g.fillStyle = '#202020'; g.fillRect(0, 0, c.width, c.height);
  const ar = im.naturalWidth / im.naturalHeight; let sw = im.naturalWidth, sh = im.naturalHeight, ox = 0, oy = 0;
  if (ar > 16 / 9) { sw = sh * 16 / 9; ox = (im.naturalWidth - sw) / 2; } else { sh = sw * 9 / 16; oy = (im.naturalHeight - sh) / 2; }
  const sx = sw / 1600, sy = sh / 900;
  [a, b].forEach((k, j) => { if (k == null) return; const tx = (k % 2) * 800, ty = Math.floor(k / 2) * 450;
    g.drawImage(im, ox + tx * sx, oy + ty * sy, 800 * sx, 450 * sy, 0, j * 470, 800, 450); CODE(g, j * 470 + 450, base + idx * 10 + k); });
  await new Promise(r => setTimeout(r, 200)); return [im.naturalWidth, im.naturalHeight]; };
